Numpy Question Practice

In [1]:
import numpy as np

In [17]:
# Assignment 1: Array Creation and Manipulation

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
arr1 = np.random.randint(1, 21, size=(5, 5))
print("Originial arr1: ")
print(arr1)

arr1[:,2]=1
print("Modified arr1: ")
print(arr1)


# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.arange(1,17).reshape(4,4)
print("\nOrginial arr2: ")
print(arr2)

np.fill_diagonal(arr2,0)
print("All diagonal elemts to 0")
print(arr2)






Originial arr1: 
[[ 9 15 18  7  6]
 [15  6  1 11 10]
 [11  3 15 17 18]
 [ 5 15  3 10  2]
 [18 14 18  7 10]]
Modified arr1: 
[[ 9 15  1  7  6]
 [15  6  1 11 10]
 [11  3  1 17 18]
 [ 5 15  1 10  2]
 [18 14  1  7 10]]

Orginial arr2: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
All diagonal elemts to 0
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [31]:
# Assignment 2: Array Indexing and Slicing

# Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr1 = np.arange(1, 37).reshape(6, 6)
print("Original array:\n", arr1)

sub_arr1 = arr1[2:5, 1:4]
print("\nSub-array (3rd to 5th rows, 2nd to 4th columns):\n", sub_arr1)

# Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr2=np.random.randint(1,101, size=(5,5))
print("Original array:",arr2)
border_arr2 = arr2.copy()
border_arr2[1:-1,1:-1] = 0
print("\nborder elements only: ",border_arr2)

Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array (3rd to 5th rows, 2nd to 4th columns):
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Original array: [[  8  10  32  92  82]
 [ 33 100  30  51  96]
 [ 31  10  72  37  32]
 [ 21  32  45  38  33]
 [ 45  73  70 100  74]]

border elements only:
  [[  8  10  32  92  82]
 [ 33   0   0   0  96]
 [ 31   0   0   0  32]
 [ 21   0   0   0  33]
 [ 45  73  70 100  74]]


In [46]:
# Assignment 3: Array Operations

# Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

A = np.random.randint(1, 11, (3, 4))
B = np.random.randint(1, 11, (3, 4))

print("Array A:\n", A)
print("Array B:\n", B)

# Element-wise operations
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A * B)
print("Division:\n", A / B)


#Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.arange(1, 17).reshape(4, 4)
print("Original array:\n", arr)

row_sum = np.sum(arr, axis=1)
col_sum = np.sum(arr, axis=0)
print("\nRow-wise sum:", row_sum)
print("\nColumn-wise sum:", col_sum)

Array A:
 [[ 2  5  5  4]
 [ 2  6 10 10]
 [ 9  6  1  7]]
Array B:
 [[3 6 9 2]
 [1 8 7 3]
 [7 3 4 9]]
Addition:
 [[ 5 11 14  6]
 [ 3 14 17 13]
 [16  9  5 16]]
Subtraction:
 [[-1 -1 -4  2]
 [ 1 -2  3  7]
 [ 2  3 -3 -2]]
Multiplication:
 [[ 6 30 45  8]
 [ 2 48 70 30]
 [63 18  4 63]]
Division:
 [[0.66666667 0.83333333 0.55555556 2.        ]
 [2.         0.75       1.42857143 3.33333333]
 [1.28571429 2.         0.25       0.77777778]]
Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum: [10 26 42 58]

Column-wise sum: [28 32 36 40]


In [51]:
# Assignment 4: Statistical Operations
# Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation,variance and normalised data of the array.

A = np.random.randint(1,101, size=(5,5))
print("\nOriginal Array: \n",A)

mean_val = np.mean(A)
median_val = np.median(A)
std_dev_val = np.std(A)
variance_val = np.var(A)

normalised_data = (A - mean_val) / std_dev_val

print("\n:Mean: ",mean_val)
print("\n:Median: ",median_val)
print("\n:Standard Deviation: ",std_dev_val)
print("\n:Variance: ",variance_val)
print("\n:Normalised Data: \n",normalised_data)



# Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).



Original Array: 
 [[20 55  9 75 34]
 [72 27 63 97 82]
 [48  1 16 50 10]
 [13 72 13 77 71]
 [57 80  7 83 67]]

:Mean:  47.96

:Median:  55.0

:Standard Deviation:  29.344137404258454

:Variance:  861.0784000000001

:Normalised Data: 
 [[-9.52830871e-01  2.39911636e-01 -1.32769280e+00  9.21478782e-01
  -4.75733868e-01]
 [ 8.19243710e-01 -7.14282370e-01  5.12538494e-01  1.67120264e+00
   1.16002728e+00]
 [ 1.36313429e-03 -1.60031966e+00 -1.08914430e+00  6.95198490e-02
  -1.29361444e+00]
 [-1.19137937e+00  8.19243710e-01 -1.19137937e+00  9.89635497e-01
   7.85165353e-01]
 [ 3.08068350e-01  1.09187057e+00 -1.39584952e+00  1.19410564e+00
   6.48851924e-01]]


In [72]:
# Assignment 5: Broadcasting
# Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr = np.random.randint(1,100, size=(3,3))
print("2D Array: \n",arr)

one_d = np.array([10,20,30])

result = one_d + arr
print("\nBroadcasting: \n",result)


# Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr1 = np.random.randint(1,100, size=(4,4))
print("\n 2D Array: \n",arr1)

one_dim = np.array([1,2,3,4])
result1 = arr1 - one_dim
print("\n Broadcasting: \n",result1)


2D Array: 
 [[33  8 86]
 [ 4  6 18]
 [88 87 86]]

Broadcasting: 
 [[ 43  28 116]
 [ 14  26  48]
 [ 98 107 116]]

 2D Array: 
 [[73 44 93 95]
 [17 18 63 10]
 [58 65 75 70]
 [77 80 21 47]]

 Broadcasting: 
 [[72 42 90 91]
 [16 16 60  6]
 [57 63 72 66]
 [76 78 18 43]]


In [79]:
# Assignment 6: Linear Algebra

# Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
arr = np.array([
    [1,2,3],
    [2,3,9],
    [5,8,7]
])

deter = np.linalg.det(arr)
inverse = np.linalg.inv(arr)
eigenvalues, eigenvectors = np.linalg.eig(arr)


print("\nDETERMINANT:",deter)
print("\nINVERSE: \n",inverse)
print("\nEIGENVALUES:\n", eigenvalues)
print("\nEIGENVECTORS:\n", eigenvectors)



# Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

matrix_multiplication = A @ B
print("\nMatrix multiplication: \n",matrix_multiplication)


DETERMINANT: 13.999999999999991

INVERSE: 
 [[-3.64285714  0.71428571  0.64285714]
 [ 2.21428571 -0.57142857 -0.21428571]
 [ 0.07142857  0.14285714 -0.07142857]]

EIGENVALUES:
 [15.04883786 -0.24454039 -3.80429746]

EIGENVECTORS:
 [[-0.24769416 -0.84640615 -0.05126104]
 [-0.60584696  0.53252373 -0.79112242]
 [-0.75604039 -0.00388694  0.60950604]]

Matrix multiplication: 
 [[22 28]
 [49 64]]


In [91]:
# Assignment 7: Advanced Array Manipulation

# Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Original Array:\n",arr)

reshaped_arr_1 = arr.reshape((1,9))
print("\n 1 X 9 array: \n",reshaped_arr_1)

reshaped_arr_2 = reshaped_arr_1.reshape((9,1))
print("\n 9 X 1 array: \n",reshaped_arr_2)



# Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr1 = np.random.randint(1,100,size=(5,5))
print("\nRandom Array",arr1)

flatten_array = arr1.flatten()
print("\nFlatten Array: \n",flatten_array)

reshaped_array = flatten_array.reshape((5,5))
print("\nReshaped to OG: \n",reshaped_array)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 1 X 9 array: 
 [[1 2 3 4 5 6 7 8 9]]

 9 X 1 array: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Random Array [[89 99  7 34 62]
 [16 39 99 45 27]
 [80 95 15 22 37]
 [83 16 32 79 24]
 [ 1 38 58 69 81]]

Flatten Array: 
 [89 99  7 34 62 16 39 99 45 27 80 95 15 22 37 83 16 32 79 24  1 38 58 69
 81]

Reshaped to OG: 
 [[89 99  7 34 62]
 [16 39 99 45 27]
 [80 95 15 22 37]
 [83 16 32 79 24]
 [ 1 38 58 69 81]]


In [ ]:
# Assignment 8: Fancy Indexing and Boolean Indexing

# Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
a = np.random.randint(1,101, size=(5,5))


rows = [0, 1, 2, 3, 4]
cols = [0, 4]

top_bottom = a[[0, 4], :]                      
left_right = a[1:4, :][:, [0, 4]]              


border_elements = np.concatenate([
    top_bottom.flatten(),
    left_right.flatten()
])

print("Original:\n", a)
print("\nBorder elements:\n", border_elements)


# Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
array = np.random.randint(1,13, size=(4,4))
print("Array: ",array)
a = array[array>10]
print("Boolean indexing array for i>10: ",a)

Original:
 [[17 42 77  7 66]
 [14 60 70 79 55]
 [60 54 55 59 45]
 [12 32 34 60 25]
 [89 58  5 95 50]]

Border elements:
 [17 42 77  7 66 89 58  5 95 50 14 55 60 45 12 25]
Array:  [[ 2  2 10  4]
 [10  8  6  6]
 [ 6  6  3  7]
 [ 1  1 11  5]]
Boolean indexing array for i>10:  [11]


In [110]:
# Assignment 9: Structured Arrays
# Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

dt = np.dtype([                                         #created a custom data type 
    ('name', 'U10'),
    ('age','i4'),
    ('weight','f4')
])

data = np.array([                                               
    ("Tony",25,68.5),
    ("Steve",320,78.9),
    ("Peter",22,63.00)
],dtype=dt)

sorted_data  = np.sort(data,order='age')
print("Sorted data by age: \n",sorted_data)



# Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

dt1 = np.dtype([
    ('x','i4'),
    ('y','i4')
])

data = np.array([
    (1,2),
    (-8,20),
    (0,9),
    (16,-5)
],dtype=dt1)

points = np.column_stack((data['x'],data['y']))
distance = np.array([[np.linalg.norm(p1-p2) for p2 in points] for p1 in points])

np.set_printoptions(precision=2, suppress=True)
print("\nEuclidean distance between each pair is: \n",distance)


Sorted data by age: 
 [('Peter',  22, 63. ) ('Tony',  25, 68.5) ('Steve', 320, 78.9)]

Euclidean distance between each pair is: 
 [[ 0.   20.12  7.07 16.55]
 [20.12  0.   13.6  34.66]
 [ 7.07 13.6   0.   21.26]
 [16.55 34.66 21.26  0.  ]]
