###Numpy

In [28]:
import numpy as np

# arr1 = np.array([1,2,3,4,5])
 # print(arr1)

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.size) #no of elements
print(arr2.ndim) #dimensions
print(arr2.dtype) #data type with how many bits stored
print(arr2.astype(float))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
2
int64
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [14]:
import numpy as np
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr)
arr[1:,2:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 8,  9],
       [13, 14]])